/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RhauFLonT4U
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { JSX, SVGProps } from "react";

export function PaymentSuccessful() {
  return (
    <div className="flex flex-col h-screen justify-center">
      <header className="flex h-16 items-center border-b px-4 md:px-6"></header>
      <main className="flex-1 flex flex-col items-center justify-center p-4 md:p-6">
        <div className="flex flex-col items-center justify-center space-y-4">
          <CheckCircleIcon className="h-12 w-12 text-green-500" />
          <h2 className="text-2xl font-bold">Payment Successful</h2>
          <p className="text-gray-500 dark:text-gray-400">
            Your order has been successfully processed.
          </p>
        </div>
      </main>
      <footer className="flex h-16 items-center border-t px-4 md:px-6 justify-center">
        <Button className="w-full">Return to Home</Button>
      </footer>
    </div>
  );
}

function Package2Icon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>,
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 1-2 2H5a2 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 1 7.24 3h9.52a2 1.8 1.1L21" />
      <path d="M12 3v6" />
    </svg>
  );
}

function CheckCircleIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>,
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  );
}
