"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/u3MIDxYbIN6
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { JSX, SVGProps, useState } from "react";

class PaymentMethod {
  "FPS" = "FPS";
  "EFT" = "EFT";
}

export function PaymentConfirmation(url: any) {
  const [paymentMethod, setPaymentMethod] = useState("EMPTY");
  console.log(url);

  return (
    <div key="1" className="flex flex-col h-screen">
      <header className="flex items-center justify-between p-4 border-b">
        <Link href="/order/summary">
          <Button size="icon" variant="ghost">
            <ArrowLeftIcon className="h-4 w-4" />
            <span className="sr-only">Back</span>
          </Button>
        </Link>
        <h1 className="text-lg font-semibold">Payment Method</h1>
        <div className="w-8" />
      </header>
      <main className="flex-1 overflow-y-auto p-4">
        <div className="mb-6">
          <h2 className="text-sm font-semibold mb-1">
            Supported Payment Methods
          </h2>
          <div className="py-4"></div>
          <a
            href={url.url}
            onClick={() => setPaymentMethod("FPS")}
            className="flex flex-col items-center pt-4"
          >
            <img className="h-88 rounded-md mx-auto" src="/payment.png" />
          </a>
        </div>
      </main>
      <footer className="p-4 text-center">
        Payment service provided by EFTPay
      </footer>
    </div>
  );
}

function ArrowLeftIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>,
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  );
}

function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
