"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/u3MIDxYbIN6
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { JSX, SVGProps, useState } from "react";

class PaymentMethod {
  "FPS" = "FPS";
  "EFT" = "EFT";
}

export function PaymentConfirmation(url: any) {
  const [paymentMethod, setPaymentMethod] = useState("EMPTY");
  console.log(url);

  return (
    <div key="1" className="flex flex-col h-screen">
      <header className="flex items-center justify-between p-4 border-b">
        <Link href="/order/summary">
          <Button size="icon" variant="ghost">
            <ArrowLeftIcon className="h-4 w-4" />
            <span className="sr-only">Back</span>
          </Button>
        </Link>
        <h1 className="text-lg font-semibold">Payment Method</h1>
        <div className="w-8" />
      </header>
      <main className="flex-1 overflow-y-auto p-4">
        <div className="mb-6">
          <h2 className="text-sm font-semibold mb-1">
            Supported Payment Methods
          </h2>
          <ul className="grid gap-4">
            <button onClick={() => setPaymentMethod("FPS")}>
              <li
                className={`flex items-center p-4 rounded-lg border ${
                  paymentMethod === "FPS" ? "bg-blue-200" : "bg-white"
                }`}
              >
                <span className="text-lg">FPS</span>
              </li>
            </button>
            <button onClick={() => setPaymentMethod("EFT")}>
              <li
                className={`flex items-center p-4 rounded-lg border ${
                  paymentMethod === "EFT" ? "bg-blue-200" : "bg-white"
                }`}
              >
                <span className="text-lg">EFT</span>
              </li>
            </button>
          </ul>
        </div>
      </main>
      <footer className="p-4 border-t">
        {paymentMethod === "EFT" ? (
          <a href={url} target="_blank" rel="noopener noreferrer">
            <button className="w-full h-10 bg-gradient-to-r from-purple-500 to-indigo-500 text-white rounded-md shadow-md transform transition hover:scale-105">
              Confirm Payment Method
            </button>
          </a>
        ) : (
          <Link href={"/order/success"}>
            <button className="w-full h-10 bg-gradient-to-r from-purple-500 to-indigo-500 text-white rounded-md shadow-md transform transition hover:scale-105">
              Confirm Payment Method
            </button>
          </Link>
        )}
      </footer>
    </div>
  );
}

function ArrowLeftIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>,
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  );
}

function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
