/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/u3MIDxYbIN6
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { JSX, SVGProps } from "react";

export function PaymentConfirmation() {
  return (
    <div key="1" className="flex flex-col h-screen">
      <header className="flex items-center justify-between p-4 border-b">
        <Link href="/order/summary">
          <Button size="icon" variant="ghost">
            <ArrowLeftIcon className="h-4 w-4" />
            <span className="sr-only">Back</span>
          </Button>
        </Link>
        <h1 className="text-lg font-semibold">Payment Method</h1>
        <div className="w-8" />
      </header>
      <main className="flex-1 overflow-y-auto p-4">
        <div className="mb-6">
          <h2 className="text-sm font-semibold mb-1">
            Supported Payment Methods
          </h2>
          <ul className="grid gap-4">
            <li className="flex items-center bg-white p-4 rounded-lg border border-gray-200 border-gray-300 dark:border-gray-800">
              <CheckIcon className="h-6 w-6 text-green-500 flex-shrink-0 mr-4" />
              <span className="text-lg">Visa</span>
            </li>
            <li className="flex items-center bg-white p-4 rounded-lg border border-gray-200 border-gray-300 dark:border-gray-800">
              <span className="text-lg">MasterCard</span>
            </li>
            <li className="flex items-center bg-white p-4 rounded-lg border border-gray-200 border-gray-300 dark:border-gray-800">
              <span className="text-lg">American Express</span>
            </li>
            <li className="flex items-center bg-white p-4 rounded-lg border border-gray-200 border-gray-300 dark:border-gray-800">
              <span className="text-lg">PayPal</span>
            </li>
          </ul>
        </div>
      </main>
      <footer className="p-4 border-t">
        <Link href={"/order/success"}>
          <button className="w-full h-10 bg-gradient-to-r from-purple-500 to-indigo-500 text-white rounded-md shadow-md transform transition hover:scale-105">
            Confirm Payment Method
          </button>
        </Link>
      </footer>
    </div>
  );
}

function ArrowLeftIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  );
}

function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
