/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/j5LzDmPhq9h
 */
export async function ProfileCredit({ id }: { id: string }) {
  const response = await fetch(
    process.env.MONGODB_API_URL + "/action/findOne",
    {
      method: "POST",
      headers: {
        apiKey: process.env.MONGODB_API_KEY as string,
        contentType: "application/json",
      },
      body: JSON.stringify({
        collection: "user",
        database: "sme-demo",
        dataSource: "RJdid",
        filter: {
          phone: id,
        },
      }),
    },
  );

  if (!response.ok) {
    return <div>Failed to load order summary</div>;
  }

  const userData = await response.json();

  return (
    <div className="p-4 py-8 max-h-screen min-h-screen bg-gradient-to-br dark:bg-gradient-to-br dark:from-blue-700 dark:to-violet-900">
      <div className="px-4 sm:px-0 mb-8">
        <h3 className="text-base font-semibold leading-7 text-gray-900">
          Account
        </h3>
        <p className="mt-1 max-w-2xl text-sm leading-6 text-gray-500">
          Personal details.
        </p>
      </div>

      <div className="border border-gray-300 rounded-md p-4 ">
        <dl className="divide-y divide-gray-100">
          <div className="px-4 py-2 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
            <dt className="text-sm font-medium leading-6 text-gray-900">
              用户名称
            </dt>
            <dd className="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
              {userData.document.userName}
            </dd>
          </div>
          <div className="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
            <dt className="text-sm font-medium leading-6 text-gray-900">
              电话号码
            </dt>
            <dd className="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
              {userData.document.phone}
            </dd>
          </div>
          <div className="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
            <dt className="text-sm font-medium leading-6 text-gray-900">DID</dt>
            <dd className="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
              DID: {userData.document.userName}/hk/HK/CN
            </dd>
          </div>
          <div className="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
            <dt className="text-sm font-medium leading-6 text-gray-900">
              用户积分
            </dt>
            <dd className="mt-1 text-3xl leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
              {userData.document.credit}
            </dd>
          </div>
        </dl>
        <div style={{ position: "absolute", right: "10px", bottom: "10px" }}>
          上次更新时间：
          {new Date().toLocaleString("en-US", { timeZone: "Asia/Shanghai" })}
        </div>
      </div>
    </div>
  );
}
