/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/j5LzDmPhq9h
 */

import Link from "next/link";

function getTotalPrice(dishes: any) {
    let totalPrice = 0;
    Object.keys(dishes).map((dish) => {
        totalPrice +=
            parseFloat(dishes[dish].price) * parseInt(dishes[dish].quantity);
    });
    return totalPrice.toFixed(2);
}

export async function ProfileCredit({ id }: { id: string }) {
    const response = await fetch(
        process.env.MONGODB_API_URL + "/action/findOne",
        {
            method: "POST",
            headers: {
                apiKey: process.env.MONGODB_API_KEY as string,
                contentType: "application/json",
            },
            body: JSON.stringify({
                collection: "user",
                database: "sme-demo",
                dataSource: "RJdid",
                filter: {
                    phone: id,
                },
            }),
        },
    );

    if (!response.ok) {
        return <div>Failed to load order summary</div>;
    }

    const userData = await response.json();

    return (
        <div key="1" className="flex flex-col h-screen bg-white">
            <header className="border-b border-gray-200 px-4 py-2">
                <h1 className="font-semibold text-lg">User Credit</h1>
                <p className="text-sm text-gray-500">
                    用户名称: {userData.document.userName}
                </p>
                <p className="text-sm text-gray-500">
                    电话号码: {userData.document.phone}
                </p>
            </header>
            <main className="flex-1 overflow-y-auto border-b border-gray-200 px-4 py-2">
                <div className="grid gap-4">
                    <div style={{fontSize: '24px'}}>
                        用户积分：{userData.document.credit}
                    </div>
                    <div style={{position: 'absolute', right: '10px', bottom: '10px'}}>
                        最近更新时间：{new Date().toLocaleString()}
                    </div>
                </div>
            </main>
        </div>
    );
}
